import {
  Activity,
  BookOpen,
  Brain,
  CalendarCheck,
  CalendarRange,
  Compass,
  NotebookText,
  Database,
  FlaskConical,
  GitBranch,
  FolderKanban,
  Home,
  Inbox,
  Target,
  Search,
  Repeat2,
  Settings,
  Shuffle,
  Timer,
  Wallet,
  type LucideIcon,
} from "lucide-react";

import type { NavIconName } from "@/shared/constants/navigation";

export const navigationIcons: Record<NavIconName, LucideIcon> = {
  home: Home,
  brain: Brain,
  search: Search,
  "calendar-check": CalendarCheck,
  "calendar-range": CalendarRange,
  timer: Timer,
  repeat: Repeat2,
  "git-branch": GitBranch,
  inbox: Inbox,
  "folder-kanban": FolderKanban,
  target: Target,
  compass: Compass,
  "book-open": BookOpen,
  "notebook-text": NotebookText,
  "flask-conical": FlaskConical,
  shuffle: Shuffle,
  activity: Activity,
  wallet: Wallet,
  database: Database,
  settings: Settings,
};
